// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGj60HE_tGpFC89FOUIX5F2TEA1DKjQQ',
    appId: '1:1024012544929:web:a1cd7852e0db33589db9e0',
    messagingSenderId: '1024012544929',
    projectId: 'gemfitpal-c1978',
    authDomain: 'gemfitpal-c1978.firebaseapp.com',
    storageBucket: 'gemfitpal-c1978.appspot.com',
    measurementId: 'G-NM4TQDT9DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0wqC_gNhlkK0pihJ0EJ8qDpva4V1-K44',
    appId: '1:1024012544929:android:e8625b6cb1ba1b8e9db9e0',
    messagingSenderId: '1024012544929',
    projectId: 'gemfitpal-c1978',
    storageBucket: 'gemfitpal-c1978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo3_h1CXhpGXin43zzJdzLCAf4K2Lybm8',
    appId: '1:1024012544929:ios:c708560c659122659db9e0',
    messagingSenderId: '1024012544929',
    projectId: 'gemfitpal-c1978',
    storageBucket: 'gemfitpal-c1978.appspot.com',
    iosClientId: '1024012544929-mo8s3gsvmadhjhh8ilgmtb2dkj05mhk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemFitpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo3_h1CXhpGXin43zzJdzLCAf4K2Lybm8',
    appId: '1:1024012544929:ios:c708560c659122659db9e0',
    messagingSenderId: '1024012544929',
    projectId: 'gemfitpal-c1978',
    storageBucket: 'gemfitpal-c1978.appspot.com',
    iosClientId: '1024012544929-mo8s3gsvmadhjhh8ilgmtb2dkj05mhk8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gemFitpal',
  );
}
